#!/usr/bin/env bash

# start by linking these buggers. npm install won't remove the links

mkdir pogostick-http/node_modules
ln -s `pwd`/pogostick-proto pogostick-http/node_modules
mkdir pogostick-browser/node_modules
ln -s `pwd`/pogostick-http pogostick-browser/node_modules/pogostick-http
ln -s `pwd`/pogostick-proto pogostick-browser/node_modules/pogostick-proto

mkdir pogostick-stream/node_modules
ln -s `pwd`/pogostick-proto pogostick-stream/node_modules/pogostick-proto

check-dir() {
	pushd $1 && \
		npm install	&& \
		npm run ci && \
		popd
}

check-dir 'pogostick-proto' && \
	check-dir 'pogostick-http' && \
	check-dir 'pogostick-browser' && \
	check-dir 'pogostick-stream'
